# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170316_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='Post text'),
        ),
    ]
