# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170316_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='article',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'post')]),
        ),
        migrations.AlterIndexTogether(
            name='tag',
            index_together=set([('name', 'post')]),
        ),
    ]
