# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 07:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170316_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Post text'),
        ),
    ]
