# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:52
from __future__ import unicode_literals

from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170322_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='path',
            field=posts.models.ListField(blank=True, default=[], verbose_name="comment's parents path"),
        ),
    ]
