# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170322_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['path'], 'verbose_name': 'Post comment', 'verbose_name_plural': 'Post comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date changed'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Add a comment:'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='path',
            field=posts.models.ListField(blank=True, default=[], editable=False, verbose_name="comment's parents path"),
        ),
    ]
