# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:22
from __future__ import unicode_literals

from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_postcomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='path',
            field=posts.models.ListField(blank=True, default=[], editable=False, verbose_name='list of ids stored in the path attribute of parent comment if exists'),
        ),
    ]
