# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
