# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:39
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170328_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.get_avatar_path),
        ),
    ]
