# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:01
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170403_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/home/gnom/djcode/blog/blog/media/img/usersuser_noimage.png', upload_to=core.helpers.get_avatar_path),
        ),
    ]
