# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170404_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='/home/gnom/djcode/blog/blog/media/profiles'),
        ),
    ]
