# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170405_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_visible',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=3, verbose_name='Show email'),
        ),
    ]
