# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 12:18
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170410_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '320x240', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='avatar cropping'),
        ),
    ]
