# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 15:30
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_avatar_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/user_noimage.png', null=True, upload_to=core.helpers.get_avatar_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='avatar cropping'),
        ),
    ]
