# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170412_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
