# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170413_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followees',
        ),
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Followees'),
        ),
    ]
